### ISSUE TITLE
hi! do you know how to solve this problem, it seems like some data will have such problem

### ISSUE THREAD

**Issue by aaa-meituo-aaa** [Shamir-Lab/SCAPP#13]
/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/scapp.py", line 474, in <module>
    main()
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/scapp.py", line 347, in main
    PARAMS.MAX_CV, PARAMS.MIN_LENGTH)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/recycle.py", line 130, in run_scapp
    thresh = np.percentile(cov_vals, 75)
  File "<__array_function__ internals>", line 6, in percentile
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3713, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3833, in _quantile_unchecked
    interpolation=interpolation)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3410, in _ureduce
    r = func(a, **kwargs)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3948, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "<__array_function__ internals>", line 6, in take
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 194, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/conda_envs/4ad4290b/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by dpellow** [comment]
As far as I can tell from the error message, the array of contig coverages is empty. This could mean that the file is empty - no contigs, or maybe it is in an unexpected format and the contig coverages are not properly parsed.
Could you let me know more about what the input is?

**Comment by dpellow** [comment]
This seems to be a problem with the input file, not SCAPP so I'm closing the issue. @aaa-meituo-aaa feel free to re-open if you think there is an issue with SCAPP.
