### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by Wanli-HE** [Shamir-Lab/SCAPP#35]
Hi ！

do you meeting this kind of error before?

this is the main program error:
Traceback (most recent call last):
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/site-packages/scapp/scapp.py", line 234, in main
    subprocess.check_call(cmd,stderr=subprocess.STDOUT, stdout=bwa_outfile, shell=True)
  File "/home/projects/ku_00041/apps/wanli/v1.4.1-plaspline/Plaspline/conda_envs/be5eeecf/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bwa mem -t 40 circular/SRR9879791_k121__scapp_out/intermediate_files/assembly_graph.nodes.fasta qc_res/SRR9879791_1_kneaddata_paired_1.fastq.gz qc_res/SRR9879791_1_kneaddata_paired_2.fastq.gz | samtools  view -buS -@ 39 - > circular/SRR9879791_k121__scapp_out/intermediate_files/reads_pe.bam' returned non-zero exit status 1.

here is the detail of the error in bwa file
bwa_log:
[mem_sam_pe] paired reads have different names: "ERR7384863.5#0", "ERR7384863.29#0"

[mem_sam_pe] paired reads have different names: "ERR7384863.4#0", "ERR7384863.28#0"

[mem_sam_pe] paired reads have different names: "ERR7384863.3#0", "ERR7384863.27#0"

[mem_sam_pe] paired reads have different names: "ERR7384863.6#0", "ERR7384863.31#0"

[mem_sam_pe] [main_samview] truncated file.
samtools view: error closing "-": -5

**Comment by dpellow** [comment]
This looks like an error due to samtools. What happens when you run the command itself:
`bwa mem -t 40 circular/SRR9879791_k121__scapp_out/intermediate_files/assembly_graph.nodes.fasta qc_res/SRR9879791_1_kneaddata_paired_1.fastq.gz qc_res/SRR9879791_1_kneaddata_paired_2.fastq.gz | samtools view -buS -@ 39 - > circular/SRR9879791_k121__scapp_out/intermediate_files/reads_pe.bam` ?

From the messages in the log file it looks like read files are not formatted as expected by samtools, can you tell if this is the case? The read names might not be in the expected format or the files might not be properly paired. Maybe this could be fixed by changing the read names or fixing the files, for example with bbmap repair.
